In [1]:
import torch
import torch.nn as nn

In [2]:
m=nn.quantized.Embedding(10,12)

In [3]:
inx=torch.randint(low=1,high=10,size=(1,10))
inx,inx.size()

(tensor([[8, 5, 7, 7, 9, 3, 3, 9, 3, 6]]), torch.Size([1, 10]))

In [4]:
inx=inx.squeeze()
inx,inx.size()

(tensor([8, 5, 7, 7, 9, 3, 3, 9, 3, 6]), torch.Size([10]))

In [5]:
output=m(inx)
output,output.size()

(tensor([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 216.,  78.,  41., 150.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [ 91., 127.,   0.,   0., 104., 105., 100., 100., 101., 110.,  44.,  32.],
         [ 92.,   2.,   0.,   0., 125.,   5., 125.,   6., 116.,   5.,   0.,   0.],
         [ 92.,   2.,   0.,   0., 125.,   5., 125.,   6., 116.,   5.,   0.,   0.],
         [ 91., 127.,   0.,   0., 104., 105., 100., 100., 101., 110.,  44.,  32.],
         [ 92.,   2.,   0.,   0., 125.,   5., 125.,   6., 116.,   5.,   0.,   0.],
         [101., 110.,  41.,  10.,  32.,  32.,  32.,  32.,   0.,   0.,   0.,   0.]]),
 torch.Size([10, 12]))

In [8]:
d=torch.mean(output,dim=1)
d

tensor([40.4167,  0.0000,  0.0000,  0.0000, 76.1667, 39.6667, 39.6667, 76.1667,
        39.6667, 32.5000])

In [12]:
torch.argmax(d)

tensor(4)

In [16]:
# use softmax convert elem in d to prob of (0,1)
m=torch.nn.Softmax()(d)
print(m)
sum=0
for i in m:
    sum+=i
sum

tensor([1.4892e-16, 4.1707e-34, 4.1707e-34, 4.1707e-34, 5.0000e-01, 7.0343e-17,
        7.0343e-17, 5.0000e-01, 7.0343e-17, 5.4297e-20])


/home/adminroot/miniconda3/envs/distill_data/lib/python3.11/site-packages/torch/nn/modules/module.py:1518: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)


tensor(1.)

In [17]:
torch.argmax(m)

tensor(4)

In [8]:
torch.empty(5,1,dtype=torch.long).fill_(50)

tensor([[50],
        [50],
        [50],
        [50],
        [50]])

In [13]:
d=torch.randint(0,20,(10,),dtype=torch.long)
d

tensor([15,  8,  6, 14, 18,  8, 18,  5, 16,  6])

In [21]:
_,ind=d.topk(2)
ind

tensor([6, 4])

In [23]:
ind.unsqueeze(-1).detach()

tensor([[6],
        [4]])

In [100]:
a=torch.randint(0,10,(1,5))
b=torch.randint(0,10,(1,5))
c=torch.randint(0,10,(1,5))
t=[a,b,c]
t,a.size()

([tensor([[3, 2, 0, 7, 9]]),
  tensor([[0, 8, 1, 6, 6]]),
  tensor([[7, 3, 7, 1, 9]])],
 torch.Size([1, 5]))

In [101]:
torch.cat(t,dim=1)

tensor([[3, 2, 0, 7, 9, 0, 8, 1, 6, 6, 7, 3, 7, 1, 9]])

In [101]:
torch.stack(t,dim=0)

tensor([[[9, 0, 9, 7, 3]],

        [[2, 2, 6, 8, 4]],

        [[1, 5, 9, 3, 6]]])

In [104]:
a=torch.randn(2,3)
a

tensor([[-0.7704,  0.5047, -1.2166],
        [ 0.3002, -1.7426,  1.3721]])

In [105]:
a.view(-1)

tensor([-0.7704,  0.5047, -1.2166,  0.3002, -1.7426,  1.3721])

In [2]:
import torch
a=torch.randn((10))
b=torch.randn((10))
a,b

(tensor([-0.4251, -1.5757,  0.7354,  1.5018,  1.0008,  0.8490,  0.8673, -1.0470,
          1.3404,  0.3551]),
 tensor([-1.5025, -0.0942, -1.0042, -0.9562, -1.1521, -0.7583, -0.5511, -2.0398,
          1.2891, -0.3689]))

In [4]:
torch.tanh(a)

tensor([-0.4012, -0.9179,  0.6264,  0.9055,  0.7619,  0.6905,  0.7000, -0.7806,
         0.8718,  0.3409])

In [5]:
torch.tanh(b)

tensor([-0.9056, -0.0939, -0.7634, -0.7426, -0.8184, -0.6401, -0.5014, -0.9667,
         0.8589, -0.3530])

In [12]:
import math
i=math.exp(a[0])
j=math.exp(-a[0])
(i-j)/(i+j)


-0.40121553911144925

In [22]:
c=torch.randn((3,4,1))
c,c.size()

(tensor([[[ 0.1849],
          [-1.5822],
          [-1.2110],
          [-0.2608]],
 
         [[-1.8215],
          [ 0.6520],
          [ 0.9071],
          [ 0.5380]],
 
         [[-1.6182],
          [-0.8522],
          [-0.2467],
          [ 0.4484]]]),
 torch.Size([3, 4, 1]))

In [31]:
c.squeeze(2).unsqueeze(1)

tensor([[[ 0.1849, -1.5822, -1.2110, -0.2608]],

        [[-1.8215,  0.6520,  0.9071,  0.5380]],

        [[-1.6182, -0.8522, -0.2467,  0.4484]]])

In [32]:
c.transpose(1,2)

tensor([[[ 0.1849, -1.5822, -1.2110, -0.2608]],

        [[-1.8215,  0.6520,  0.9071,  0.5380]],

        [[-1.6182, -0.8522, -0.2467,  0.4484]]])

In [36]:
input=torch.randn(10,1,4)
mat2=torch.randn(10,4,5)
torch.bmm(input,mat2)

tensor([[[ 0.5343, -0.7017,  1.1302, -4.0544, -4.7434]],

        [[ 0.3598, -1.7984, -0.3229,  1.5098,  5.6372]],

        [[ 0.1253,  0.8635, -0.4858, -0.2872, -0.6174]],

        [[ 0.3907,  1.7180, -2.0073, -0.9748, -0.0188]],

        [[-0.6374, -1.8763, -0.3272, -2.8946,  1.3741]],

        [[ 3.4298,  4.5729,  3.6315,  2.2706, -4.1750]],

        [[-0.7933,  1.4687,  0.4660,  0.1995,  0.6310]],

        [[ 1.3289, -1.0014, -0.2890,  0.3842, -0.7253]],

        [[ 3.6787, -2.1554,  0.0613,  0.7050, -0.8340]],

        [[-1.9287, -0.7844, -1.4627,  1.2550, -1.5534]]])

In [97]:

rnn=torch.nn.GRU(10,20,2,batch_first=True)
input=torch.randn(3,5,10) # [batch_size,seq_len,hidden_size]
h0=torch.randn(2,3,20) #[num_layer,batch_size,hidden_size]
output,hn=rnn(input,h0)

In [99]:
output.size(),hn.size()
hn

tensor([[[ 0.0966,  0.0850, -0.0144, -0.2492,  0.0882, -0.0528, -0.0668,
           0.1133,  0.0476, -0.1433,  0.0973,  0.1918, -0.3929, -0.3457,
          -0.1468, -0.0566,  0.0626, -0.0078, -0.1233,  0.2845],
         [ 0.2307,  0.0486,  0.2958,  0.1308,  0.1187, -0.0956,  0.0679,
           0.0884, -0.0963,  0.0533,  0.0500,  0.1931,  0.0765, -0.0785,
           0.0665, -0.0759, -0.1055,  0.3894, -0.0139,  0.0137],
         [ 0.0509,  0.0526,  0.2739,  0.1720, -0.3999,  0.0031, -0.4146,
           0.2687, -0.0571,  0.0435,  0.1527,  0.4541, -0.2086, -0.2708,
           0.2138, -0.2714, -0.2830,  0.0140,  0.2017,  0.0535]],

        [[-0.0986, -0.0183,  0.2382,  0.2471, -0.2534,  0.0755, -0.1397,
          -0.0832,  0.0924, -0.1394, -0.0636, -0.2700,  0.1233, -0.0867,
           0.0151, -0.3005, -0.0531, -0.1015,  0.0633, -0.0560],
         [-0.3238, -0.0675,  0.2915,  0.3658, -0.4095, -0.0069, -0.2255,
          -0.0271,  0.0368, -0.0059, -0.0390, -0.3401,  0.2954, -0.0949,
        

In [45]:
tmp=torch.randn(2,3,4)
tmp

tensor([[[ 1.4571,  0.5620, -0.6793,  1.5398],
         [-2.3515, -0.1488,  0.2870, -0.3212],
         [ 0.6668,  1.3626, -0.3457, -0.7709]],

        [[ 0.0990, -1.0614,  0.2690, -0.9231],
         [ 1.0972,  0.2956,  0.8115, -1.0920],
         [-0.3299,  1.3630, -0.9358, -0.0810]]])

In [46]:
tmp.permute(1,0,2)

tensor([[[ 1.4571,  0.5620, -0.6793,  1.5398],
         [ 0.0990, -1.0614,  0.2690, -0.9231]],

        [[-2.3515, -0.1488,  0.2870, -0.3212],
         [ 1.0972,  0.2956,  0.8115, -1.0920]],

        [[ 0.6668,  1.3626, -0.3457, -0.7709],
         [-0.3299,  1.3630, -0.9358, -0.0810]]])

In [48]:
wv=torch.randn(4,5,6)
uv=torch.randn(4,5,6)
L=torch.nn.Linear(6,6)

In [53]:
wv=wv.permute(1,0,2)

In [54]:
vv=L(wv)+L(uv)

RuntimeError: The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 1

In [52]:
vv.size()

torch.Size([4, 5, 6])

In [102]:
top=torch.randn(3,1,5)
top

tensor([[[ 1.0897,  1.3601,  0.6858, -0.2313,  0.2795]],

        [[-0.2727,  0.6991,  0.2556, -0.6225, -1.8562]],

        [[ 0.0202,  0.8290,  0.3112, -1.7516, -0.4652]]])

In [103]:
_,topi=top.topk(1)
topi

tensor([[[1]],

        [[1]],

        [[1]]])

In [104]:
topi.size()

torch.Size([3, 1, 1])

In [106]:
topi.squeeze(-1)

tensor([[1],
        [1],
        [1]])